theme: jekyll-theme-modernist
encoding: 'utf-8'
language: 'en-us'

# Site Settings
title: Andrew Sai's Page
author:
  name: Andrew Sai
  email: andrewadjahsai@gmail.com
description: Ghanaian with a passion for <br />open source, tech, and web development
meta_description: Andrew Sai, PhD — Ghanaian with a passion for open source, tech, and web development
avatar_img: https://github.com/funandyx/andrewsai/blob/master/Andy1.jpeg


# 3rd-party
social:
  github: funandyx
  twitter: niiadjahsai
  instagram: funandyx


